import { TransactionType } from '@prisma/client';

export const defaultCategories = [
  // ====== 支出 ======
  { name: '餐饮', icon: '🍽️', color: '#FFB86B', type: TransactionType.expense, sort: 10 },
  { name: '购物', icon: '🛍️', color: '#FF8A65', type: TransactionType.expense, sort: 20 },
  { name: '日用', icon: '🧴', color: '#90CAF9', type: TransactionType.expense, sort: 30 },
  { name: '交通', icon: '🚌', color: '#7C8CFF', type: TransactionType.expense, sort: 40 },
  { name: '蔬菜', icon: '🥕', color: '#66BB6A', type: TransactionType.expense, sort: 50 },
  { name: '水果', icon: '🍒', color: '#EF5350', type: TransactionType.expense, sort: 60 },
  { name: '零食', icon: '🧁', color: '#F48FB1', type: TransactionType.expense, sort: 70 },
  { name: '运动', icon: '🚴', color: '#42A5F5', type: TransactionType.expense, sort: 80 },
  { name: '娱乐', icon: '🎮', color: '#A78BFA', type: TransactionType.expense, sort: 90 },
  { name: '通讯', icon: '📞', color: '#26A69A', type: TransactionType.expense, sort: 100 },
  { name: '服饰', icon: '👗', color: '#EC407A', type: TransactionType.expense, sort: 110 },
  { name: '住房', icon: '🏠', color: '#60A5FA', type: TransactionType.expense, sort: 120 },
  { name: '居家', icon: '🛋️', color: '#8D6E63', type: TransactionType.expense, sort: 130 },
  { name: '烟酒', icon: '🍷', color: '#AB47BC', type: TransactionType.expense, sort: 140 },
  { name: '汽车', icon: '🚗', color: '#5C6BC0', type: TransactionType.expense, sort: 150 },
  { name: '数码', icon: '📱', color: '#78909C', type: TransactionType.expense, sort: 160 },
  { name: '培训', icon: '👤', color: '#FFA726', type: TransactionType.expense, sort: 170 },
  { name: '孩子', icon: '👶', color: '#FFCA28', type: TransactionType.expense, sort: 180 },
  { name: '美容', icon: '💄', color: '#F06292', type: TransactionType.expense, sort: 190 },
  { name: '长辈', icon: '👴', color: '#A1887F', type: TransactionType.expense, sort: 200 },
  { name: '社交', icon: '🍻', color: '#FF7043', type: TransactionType.expense, sort: 210 },
  { name: '旅行', icon: '✈️', color: '#29B6F6', type: TransactionType.expense, sort: 220 },
  { name: '医疗', icon: '🏥', color: '#34D399', type: TransactionType.expense, sort: 230 },
  { name: '书籍', icon: '📖', color: '#8D6E63', type: TransactionType.expense, sort: 240 },
  { name: '学习', icon: '🎓', color: '#FBBF24', type: TransactionType.expense, sort: 250 },
  { name: '宠物', icon: '🐶', color: '#BCAAA4', type: TransactionType.expense, sort: 260 },
  { name: '礼金', icon: '💴', color: '#EF5350', type: TransactionType.expense, sort: 270 },
  { name: '礼物', icon: '🎁', color: '#E91E63', type: TransactionType.expense, sort: 280 },
  { name: '办公', icon: '💼', color: '#607D8B', type: TransactionType.expense, sort: 290 },
  { name: '维修', icon: '🔧', color: '#9E9E9E', type: TransactionType.expense, sort: 300 },
  { name: '捐赠', icon: '❤️', color: '#E57373', type: TransactionType.expense, sort: 310 },
  { name: '彩票', icon: '🎰', color: '#7E57C2', type: TransactionType.expense, sort: 320 },
  { name: '亲友', icon: '👨‍👩‍👧', color: '#4DB6AC', type: TransactionType.expense, sort: 330 },
  { name: '快递', icon: '📦', color: '#FF8A65', type: TransactionType.expense, sort: 340 },

  // ====== 收入 ======
  { name: '工资', icon: '💰', color: '#00D4C8', type: TransactionType.income, sort: 10 },
  { name: '兼职', icon: '💼', color: '#42A5F5', type: TransactionType.income, sort: 20 },
  { name: '理财', icon: '📈', color: '#66BB6A', type: TransactionType.income, sort: 30 },
  { name: '奖金', icon: '🏆', color: '#FFB300', type: TransactionType.income, sort: 40 },
  { name: '红包', icon: '🧧', color: '#EF5350', type: TransactionType.income, sort: 50 },
  { name: '退款', icon: '💸', color: '#26C6DA', type: TransactionType.income, sort: 60 },
  { name: '报销', icon: '🧾', color: '#9CCC65', type: TransactionType.income, sort: 70 },
  { name: '其它收入', icon: '＋', color: '#34D399', type: TransactionType.income, sort: 99 },
];
